### PR TITLE
fix(project): Allow Component.ts

### LINKED ISSUE #1242: [v5/next] Serving a component type project written in TypeScript fails
Hi team,

@marianfoo migrated a UI5 project to the project type `component` and the UI5 serve command failed because no `Component.js` is present in a TypeScript project.

# Log
```bash
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/adp-tooling to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/adp-tooling
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/project-access to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/project-access
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/feature-toggle to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/feature-toggle
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/logger to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/logger
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/telemetry to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/telemetry
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/guided-answers-helper to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/guided-answers-helper
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/store to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/store
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/ui5-config to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/ui5-config
verb graph:providers:NodePackageDependencies Resolved module @sap-ux/ui5-info to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@sap-ux/ui5-info
verb graph:providers:NodePackageDependencies Resolving module path for '@zowe/secrets-for-zowe-sdk'...
verb graph:providers:NodePackageDependencies Resolved module @zowe/secrets-for-zowe-sdk to path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/node_modules/@zowe/secrets-for-zowe-sdk
verb graph:projectGraphBuilder Creating module ui5-cc-spreadsheetimporter...
verb graph:projectGraphBuilder Creating module @sap-ux/ui5-middleware-fe-mockserver...
verb graph:projectGraphBuilder Creating module @sap/ux-specification...
verb graph:projectGraphBuilder Creating module @sap/ux-ui5-tooling...
verb graph:projectGraphBuilder Creating module @ui5/cli...
verb graph:projectGraphBuilder Creating module estree-walker...
verb graph:projectGraphBuilder Creating module ui5-middleware-serveframework...
verb graph:projectGraphBuilder Creating module ui5-middleware-simpleproxy...
verb graph:projectGraphBuilder Creating module ui5-middleware-ui5...
verb graph:projectGraphBuilder Creating module ui5-task-btp-manifest...
verb graph:projectGraphBuilder Creating module ui5-tooling-modules...
verb graph:Module Could not find any build manifest in module ui5-cc-spreadsheetimporter
verb graph:Module Could not find any build manifest in module @sap-ux/ui5-middleware-fe-mockserver
verb graph:Module Could not find any build manifest in module @sap/ux-specification
verb graph:Module Could not find any build manifest in module @sap/ux-ui5-tooling
verb graph:Module Could not find any build manifest in module @ui5/cli
verb graph:Module Could not find any build manifest in module estree-walker
verb graph:Module Could not find any build manifest in module ui5-middleware-serveframework
verb graph:Module Could not find any build manifest in module ui5-middleware-simpleproxy
verb graph:Module Could not find any build manifest in module ui5-middleware-ui5
verb graph:Module Could not find any build manifest in module ui5-task-btp-manifest
verb graph:Module Could not find any build manifest in module ui5-tooling-modules
verb graph:Module Could not find a configuration file for module @sap/ux-specification
verb graph:Module Could not find a configuration file for module @ui5/cli
verb graph:Module Could not find a configuration file for module estree-walker
verb graph:Module Configuration for module ui5-cc-spreadsheetimporter is provided in YAML file at ui5.yaml
verb graph:Module Configuration for module @sap-ux/ui5-middleware-fe-mockserver is provided in YAML file at ui5.yaml
verb specifications:types:ServerMiddleware Detected legacy Specification Version 1.0, defined for extension sap-fe-mockserver. Attempting to migrate the project to a supported specification version...
verb graph:Module Module @sap-ux/ui5-middleware-fe-mockserver contains extension sap-fe-mockserver
verb graph:Module Configuration for module ui5-middleware-serveframework is provided in YAML file at ui5.yaml
verb graph:Module Module ui5-middleware-serveframework contains extension ui5-middleware-serveframework
verb graph:Module Configuration for module @sap/ux-ui5-tooling is provided in YAML file at ui5.yaml
verb graph:Module Module @sap/ux-ui5-tooling contains extension fiori-tools-appreload
verb graph:Module Module @sap/ux-ui5-tooling contains extension fiori-tools-proxy
verb graph:Module Module @sap/ux-ui5-tooling contains extension fiori-tools-preview
verb graph:Module Module @sap/ux-ui5-tooling contains extension fiori-tools-servestatic
verb graph:Module Module @sap/ux-ui5-tooling contains extension deploy-to-abap
verb graph:Module Configuration for module ui5-middleware-simpleproxy is provided in YAML file at ui5.yaml
verb graph:Module Module ui5-middleware-simpleproxy contains extension ui5-middleware-simpleproxy
verb graph:Module Configuration for module ui5-task-btp-manifest is provided in YAML file at ui5.yaml
verb graph:Module Module ui5-task-btp-manifest contains extension ui5-task-btp-manifest
verb graph:Module Configuration for module ui5-middleware-ui5 is provided in YAML file at ui5.yaml
verb graph:Module Module ui5-middleware-ui5 contains extension ui5-middleware-ui5
verb graph:Module Configuration for module ui5-tooling-modules is provided in YAML file at ui5.yaml
verb graph:Module Module ui5-tooling-modules contains extension ui5-tooling-modules-middleware
verb graph:Module Module ui5-tooling-modules contains extension ui5-tooling-modules-task
verb specifications:types:Component Path mapping for component project ui5-cc-spreadsheetimporter-v2-4-0:
verb specifications:types:Component   Physical root path: /Users/xxx/DEV/ui5-cc-spreadsheetimporter/packages/ui5-cc-spreadsheetimporter
verb specifications:types:Component   Mapped to:
verb specifications:types:Component     /resources/ => src
verb specifications:types:Component     /test-resources/ => test [does not exist]
verb specifications:types:Component Namespace of project ui5-cc-spreadsheetimporter-v2-4-0 is cc/spreadsheetimporter/v2_4_0 (from manifest.json)

⚠️  Process Failed With Error

Error Message:
Unable to find required file Component.js in component project ui5-cc-spreadsheetimporter-v2-4-0


Stack Trace:
Error: Unable to find required file Component.js in component project ui5-cc-spreadsheetimporter-v2-4-0
    at Component._ensureComponent (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/types/Component.js:297:10)
    at async Component._parseConfiguration (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/types/Component.js:178:3)
    at async Component.init (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/specifications/Project.js:38:3)
    at async file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/Module.js:165:17
    at async Promise.all (index 0)
    at async Module._getSpecifications (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/Module.js:160:17)
    at async file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:202:34
    at async Promise.all (index 0)
    at async projectGraphBuilder (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:162:15)
    at async graphFromPackageDependencies (file:///Users/xxx/.npm/_npx/4cc39c7434561d9a/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/graph.js:73:23)
If you think this is an issue of the UI5 CLI, you might report it using the following URL: https://github.com/UI5/cli/issues/new/choose
npm error Lifecycle script `serve` failed with error:
npm error code 1
npm error path /Users/xxx/DEV/ui5-cc-spreadsheetimporter/examples/packages/ordersv4fe
npm error workspace ordersv4fe136@0.0.1
npm error location /Users/xxx/DEV/ui5-cc-spreadsheetimporter/examples/packages/ordersv4fe
npm error command failed
npm error command sh -c UI5_CLI_NO_LOCAL=true npx --yes @ui5/cli@5.0.0-alpha.1 serve --loglevel verbose
```

# Code
https://github.com/spreadsheetimporter/ui5-cc-spreadsheetimporter/tree/chore/ui5-cli-v5-component

### PR DESCRIPTION
**Pull request by maxreichmann**
Fixes #1242.
This allows the use of TS for Component files.

### CODE REVIEW

File: packages/project/lib/specifications/types/Component.js [hunk 1]
```diff
@@ -291,11 +291,21 @@ class Component extends ComponentProject {
...
 
 	async _ensureComponent() {
-		// Ensure that a Component.js exists
-		const componentResource = await this._getRawSourceReader().byPath("/Component.js");
-		if (!componentResource) {
+		// Throw if neither Component.js nor Component.ts is present
+		// or if both are present
+		const componentJSResource = await this._getRawSourceReader().byPath("/Component.js");
+		const componentTSResource = await this._getRawSourceReader().byPath("/Component.ts");
+		if (componentJSResource && componentTSResource) {
```
Comment (d3xter666) [inline packages/project/lib/specifications/types/Component.js]: I would expect this to be a real use case, where the output dir is the same as source dir.

In such case, IMO we should check only the TS file as it must be the source for the JS.

Let the others say what do they think about it

Comment (maxreichmann) [reply packages/project/lib/specifications/types/Component.js]: @RandomByte

Comment (RandomByte) [reply packages/project/lib/specifications/types/Component.js]: I agree, I think it should ne fine if both are present. We only want to ensure that at least one Component file exists

Comment (maxreichmann) [reply packages/project/lib/specifications/types/Component.js]: Done in 1f661f3

**Review by RandomByte — DISMISSED** [review]
LGTM 🤝

File: packages/project/lib/specifications/types/Component.js [hunk 2]
```diff
@@ -291,11 +291,15 @@ class Component extends ComponentProject {
 	}
 
 	async _ensureComponent() {
-		// Ensure that a Component.js exists
-		const componentResource = await this._getRawSourceReader().byPath("/Component.js");
+		// Throw if neither Component.js nor Component.ts is present
+		// or if both are present
```
Comment (d3xter666) [inline packages/project/lib/specifications/types/Component.js]: This comment seems outdated now

Comment (maxreichmann) [reply packages/project/lib/specifications/types/Component.js]: Done

**Review by d3xter666 — APPROVED** [review]
